### ISSUE TITLE
Copying links of bookmarks

### ISSUE THREAD

**Issue by Ibanez1130** [amoscardino/linkthing#22]
Enable the copying of links, when holding a certain bookmark. I don't always want to open a website, but sometimes I just want to get the link.

**Comment by amoscardino** [comment]
As much as I like the idea of using the long-press context menu, it apparently does not play nice with the sliding items that are currently in use. I'm sure I could figure it out, but it seems a lot easier to simply add a new sliding item next to edit and share for copy.
