### ISSUE TITLE
Quick add bookmark by putting LinkThing to iOS share menu?

### ISSUE THREAD

**Issue by omltcat** [amoscardino/linkthing#30]
Correct me if I’m wrong be it seems the only way to add a bookmark now is to copy the url, open LinkThing and paste it?  
Is possible to add LinkThing to the share menu so that in Safari you can just share the current page to LinkThing and have the bookmark added in one click? 

Thanks for the amazing app.

**Comment by amoscardino** [comment]
You are correct. Adding bookmarks is currently limited to the add view in the app. The clipboard URL detection makes it a bit easier, but it’s not quite as good as a share sheet extension. This is already logged in #20 so you can follow along with that issue and I will close this one as a duplicate.
