### ISSUE TITLE
can I user https://demo.linkding.link/bookmarks and its token to test API 

### ISSUE THREAD

**Issue by matthewxu** [amoscardino/linkthing#39]
can I user site:https://demo.linkding.link/bookmarks and its token to test API;
when I use IOS client from  https://github.com/amoscardino/linkthing, it shows wrong settings.

**Comment by amoscardino** [comment]
That demo site has a strange configuration (detailed here: https://github.com/sissbruecker/linkding/issues/408). If you can connect to it from your device’s browser, then you should be able to use the app. The best bet is to try the health endpoint from your device: https://demo.linkding.link/health

**Comment by matthewxu** [comment]
thx，it looks like I have something wrong with the net connection using iphone。when I use mac and set proxy，it is ok
